#########################################################
##                  Storage Settings                   ##
#########################################################

Storage:
  # The database system used to store plugin's data.
  # Available systems:
  #   - h2
  #   - mysql
  Type: "h2"

  # Credentials required to connect to the database:
  IP: 127.0.0.1
  Port: 3306
  Database: "database"
  User: "username"
  Password: "password"
  Table Prefix: "supercore_"

#########################################################
##                  Language Settings                  ##
#########################################################

Laguage:
  Default Language:
    - "english.yml"
  Languages:
    - "english.yml"

#########################################################
##                 User Homes Settings                 ##
#########################################################

Homes:
  # When someone sets his home without specifying a name,
  # home's name will be the default value set here
  Default Home Name: "home"

  # The limit of homes that a player can set.
  # Permission: supercore.home.limit.<group>
  Home Limits:
    default: 3
    vip: 5
    vip+: 7