name: SuperCore
version: 0.2.7
main: me.Stefan923.SuperCore.SuperCore
description: Provides a core set of commands and server utilities.
softdepend: [PlaceholderAPI]
authors: [Stefan923]

commands:
  core:
    description: Infos about this plugin.
    aliases: [corelite, supercore, supercorelite, score, scorelite]
  adminchat:
    description: Special chat for admins.
    aliases: [superadminchat, sadminchat, achat, superachat, sachat, ac, superac, sac]
  adventure:
    description: Changes gamemode to adventure.
    aliases: [superadventure, gma, supergma]
  broadcast:
    description: Sends a message to all online players.
    aliases: [superbroadcast, sbroadcast, bc, superbc, sbc]
  creative:
    description: Changes gamemode to creative.
    aliases: [supercreative, gmc, supergmc]
  donorchat:
    description: Special chat for donors.
    aliases: [superdonorchat, sdonorchat, dchat, superdchat, sdchat, dc, superdc, sdc]
  fly:
    description: Enable/Disable flight mode.
    aliases: [superfly, sfly]
  gamemode:
    description: Change your or others gamemode.
    aliases: [supergamemode, sgamemode, gm, supergm, sgm]
  god:
    description: Change your or others god mode.
    aliases: [supergod, sgod]
  heal:
    description: Refills player's health state.
    aliases: [superheal, sheal]
  helpop:
    description: Special chat to request help.
    aliases: [superhelpop, shelpop, superreport, sreport, report]
  language:
    description: Shows list of online players.
    aliases: [superlanguage, slanguage, lang, superlang, slang]
  list:
    description: Shows list of online players.
    aliases: [superlist, slist, who, superwho, swho]
  nick:
    description: Change your name.
    aliases: [supernick, snick, nickname, supernickname, snickname]
  seen:
    description: Shows a player's last online session.
    aliases: [superseen, sseen]
  spectator:
    description: Changes gamemode to spectator.
    aliases: [superspectator, gmsp, supergmsp]
  survival:
    description: Changes gamemode to survival.
    aliases: [supersurvival, gms, supergms]
  tp:
    description: Changes gamemode to survival.
    aliases: [supertp, teleport, superteleport]
  tptoggle:
    description: Toggles own or others teleportation.
    aliases: [supertptoggle, toggletp, supertoggletp]
  whois:
    description: Shows information about a player.
    aliases: [superwhois]

permissions:
  supercore.admin:
    description: Acces to powerfull commands, like /core reload.
    default: op
  supercore.adminchat.send:
    description: Use adminchat command.
    default: op
  supercore.adminchat.receive:
    description: Receive messages on adminchat.
    default: op
  supercore.donorchat.send:
    description: Use donorchat command.
    default: op
  supercore.donorchat.receive:
    description: Receive messages on donorchat.
    default: op
  supercore.fly:
    description: Use fly command.
    default: op
  supercore.gamemode:
    description: Use gamemode command.
    default: op
  supercore.gamemode.others:
    description: Use gamemode command on other players.
    default: op
  supercore.gamemode.survival:
    description: Change gamemode to survival.
    default: op
  supercore.gamemode.creative:
    description: Change gamemode to creative.
    default: op
  supercore.gamemode.adventure:
    description: Change gamemode to adventure.
    default: op
  supercore.gamemode.spectator:
    description: Change gamemode to spectator.
    default: op
  supercore.god:
    description: Use god command.
    default: op
  supercore.god.others:
    description: Use god command on others.
    default: op
  supercore.helpop.send:
    description: Use helpop command.
    default: op
  supercore.helpop.receive:
    description: Receive messages on helpop.
    default: op
  supercore.language:
    description: Change your language.
    default: op
  supercore.list:
    description: Use list command.
    default: op
  supercore.list.default:
    description: Appear on online list as default player.
    default: true
  supercore.nick:
    description: Use nick command.
    default: op
  supercore.nick.format:
    description: Use formatting codes in nickname.
    default: op
  supercore.tptoggle:
    description: Use tptoggle command.
    default: op
  supercore.tptoggle.others:
    description: Use tptoggle command on others.
    default: op
  supercore.whois:
    description: Use whois command.
    default: op
  supercore.updatechecker:
    description: Shows a message when an update is available.
    default: op